site_name: Voron 0.2 Fly Gemini V3 Setup Guide


nav:
  - Home: index.md
  - Installation: installation.md
  - Updating: updating.md
  - Extras: extras.md


theme:
  name: material
  features:
    - navigation.top
    - navigation.path
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  version:
    provider: mike
